curtin: Mention how to install required packages
When running tox on a vanilla Ubuntu 24.04 I get this error:

   In file included from python/acquire-item.cc:24:
   python/apt_pkgmodule.h:14:10: fatal error: apt-pkg/hashes.h:
     No such file or directory
         14 | #include <apt-pkg/hashes.h>
            |          ^~~~~~~~~~~~~~~~~~

Add a note in the hacking instructions to help with this, pointing to
the setup script and the make target.

Signed-off-by: Simon Glass <simon.glass@canonical.com>