storage-config: don't crash in presence of a VG with no LV
While it is unusual to have a VG with no LV yet, it is a possibility.
For instance, if the installer does not support a specific VG configuration,
users typically try to create the VG themselves and expect the installer to
populate it with LV-s (spoiler, it isn't supported).

We changed probert so that is also reports VG-s with no LV. But when it does
so, it can report a LVM config that has a "virtual_groups" key with no
"logical_volumes" key.

  {
    "lvm": {
      "virtual_groups": ...,
      "physical_volumes": ...
    }
  }

This was crashing curtin's storage-config, which expected the "logical_volumes"
key to always be present if the "virtual_groups" key is.

  Traceback (most recent call first)
   [...]
    File "curtin/storage_config.py", line 1470, in extract_storage_config
      found_cfgs, found_errs = parser.parse()
                               ^^^^^^^^^^^^^^
    File "curtin/storage_config.py", line 1071, in parse
      for lv_name, lv_config in self.class_data['logical_volumes'].items():
                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  KeyError: 'logical_volumes'

Fixed by considering an empty dictionary of logical volumes if the key is not
present.

LP: #2143299

Signed-off-by: Olivier Gayot <olivier.gayot@canonical.com>