lvm: ignore missing PVs when checking which are in a VG
Previously, in the presence of missing PVs in a VG, the list returned by
get_pvols_in_volgroup("ubuntu-vg") contained "[unknown]" entries.

When wiping the PVs, we would attempt to quickzero an "[unknown]" block device
which would fail because there is no such disk.

  Traceback (most recent call last):
    File "curtin/block/clear_holders.py", line 148, in shutdown_lvm
      block.quick_zero(pv, partitions=False)
      ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
    File "curtin/block/__init__.py", line 1194, in quick_zero
      raise ValueError("%s: not an existing file or block device" % path)
  ValueError: [unknown]: not an existing file or block device

Fixed by excluding missing PVs.

LP: #2142196

Signed-off-by: Olivier Gayot <olivier.gayot@canonical.com>
(cherry picked from commit 0cef5118064a068189c49397a196128810202887)

Modified to:
 * operate with pvdisplay(8) instead of pvs(8)
 * include a unit test